version: '3.7'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    ports:
      - "4566:4566"
    volumes:
      - type: bind
        source: "./aws"
        target: "/docker-entrypoint-initaws.d"