version: '3.7'
services:

  database:
    image: "topaztechnology/mssql-server-linux:latest"
    ports:
      - ${DB_PORT}:1433
    environment:
      SA_PASSWORD: "${DB_PASSWORD}"
      ACCEPT_EULA: "Y"

  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - AWS_ACCESS_KEY_ID=foobar
      - AWS_SECRET_ACCESS_KEY=foobar
    ports:
      - "4566:4566"
    volumes:
      - type: bind
        source: "./aws"
        target: "/docker-entrypoint-initaws.d"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - ${RABBITMQ_SERVICE_PORT}:5672
        - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment: 
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  # frontend:
  #   build: 
  #     context: Frontend
  #   ports: 
  #     - "8080:80"